kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: deployment-demo-canary 
  labels:
    app: deployment-demo 
    
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: deployment-demo 
      track: canary 
  template:
    metadata: 
      labels:
        app: deployment-demo 
        track: canary #
        
    spec: 
      containers: 
        - name: deployment-demo-canary 
          image: ECRIMAGEURLHERE:canary 
          imagePullPolicy: Always 
          ports:
            - containerPort: 80 
          resources: 
            limits: 
              cpu: 500m 
            requests: 
              cpu: 200m 
      restartPolicy: Always